#pragma once

namespace angel::io {
enum TerminalColour {
    TERMINAL_COLOUR_NONE,
    TERMINAL_COLOUR_RED,
    TERMINAL_COLOUR_BLUE,
    TERMINAL_COLOUR_LIGHTBLUE,
    TERMINAL_COLOUR_GREEN,
    TERMINAL_COLOUR_GRAY,
    TERMINAL_COLOUR_LIGHTGRAY,
    TERMINAL_COLOUR_PURPLE,
    TERMINAL_COLOUR_YELLOW,
    TERMINAL_COLOUR_WHITE,
    TERMINAL_COLOUR_BLACK,
    TERMINAL_COLOUR_MAX,
};
}
